name: List AWS S3 Buckets

on:
  workflow_dispatch:

env:
  AWS_IAM_ROLE : "github-actions-role"
  AWS_REGION : "eu-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  aws-s3-ls:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHubActions
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.AWS_IAM_ROLE }}

    - name: Run aws s3 ls
      run: aws s3 ls
